const EVENTS_NUM = 17;
const EDIT_EVENT_IDX = 0;
const FIRST_EVENT_TO_SHOW_IDX = 1;

const INFO_SENTENCE_MAX_NUM = 5;
const OFFERS_MAX_NUM = 5;
const PHOTOS_MAX_NUM = 4;
const OFFER_PRICE = {
  MIN: 10,
  MAX: 100,
};
const EVENT_PRICE = {
  MIN: 10,
  MAX: 500,
};

export {
  EVENTS_NUM,
  EDIT_EVENT_IDX,
  FIRST_EVENT_TO_SHOW_IDX,
  INFO_SENTENCE_MAX_NUM,
  OFFERS_MAX_NUM,
  PHOTOS_MAX_NUM,
  OFFER_PRICE,
  EVENT_PRICE,
};
